Repository sequelize/sequelize, pull requests merged in 2018-10, with the labels that each got.

#9984 fix(sum): returns 0 when is empty matching
  lib/model.js
  lib/query-interface.js
  test/integration/model/sum.test.js
Labels: pr:needs work

#10045 fix(associations): enable overwrite the name in unique constraint
  docs/associations.md
  lib/associations/belongs-to-many.js
  lib/model.js
  test/integration/associations/belongs-to-many.test.js
  test/integration/model/upsert.test.js
  test/unit/associations/belongs-to-many.test.js
Labels: backport

#9735 Scopes with foreign key
  lib/model.js
  test/integration/model/scope/associations.test.js
  test/unit/model/scope.test.js
Labels: discussion
