Repository sequelize/sequelize, pull requests merged in 2019-08, with the labels that each got.

#11249 Fix: postgresql's ensureEnums (#11053)
  lib/dialects/postgres/query-interface.js
  test/integration/dialects/postgres/dao.test.js
  test/integration/query-interface/createTable.test.js
Labels: dialect: postgres, status: awaiting investigation, type: bug

#11279 docs: fix minor typo
  lib/sequelize.js
  types/lib/sequelize.d.ts
Labels: status: awaiting maintainer, type: docs

#11282 style(spacing): add spacing around infix operators rules in eslint
  .eslintrc.json
  lib/dialects/abstract/query-generator.js
  lib/dialects/mysql/query.js
  lib/dialects/postgres/query.js
  lib/dialects/sqlite/query.js
  lib/model.js
  lib/sequelize.js
  test/integration/instance/update.test.js
  test/integration/sequelize.test.js
  test/integration/utils.test.js
  test/unit/associations/belongs-to-many.test.js
  test/unit/associations/has-many.test.js
  test/unit/sql/select.test.js
  test/unit/sql/where.test.js
Labels: status: awaiting maintainer, type: other

#11281 perf: remove unnecessary cloneDeep calls
  lib/associations/has-many.js
  lib/model.js
  lib/query-interface.js
Labels: status: awaiting maintainer, type: performance, type: refactor

#11286 docs(data-types): fix typo
  lib/data-types.js
Labels: status: awaiting maintainer, type: docs

#11299 Remove duplicate code
  lib/transaction.js
Labels: status: awaiting maintainer, type: refactor

#11277 feat(postgres): add function variables for postgres
  lib/dialects/postgres/query-generator.js
  lib/query-interface.js
  test/integration/dialects/postgres/query-interface.test.js
Labels: dialect: postgres, status: awaiting maintainer, type: feature

#11290 docs(association): Name model that association is missing from
  lib/model.js
Labels: status: awaiting maintainer, type: other

#11292 fix(types): use correct `this` value when initializing getterMethods
  types/lib/model.d.ts
  types/test/model.ts
Labels: status: awaiting maintainer, type: typescript

#11293 fix(types): return a usable type when using the sequelize.models lookup
  types/lib/sequelize.d.ts
  types/test/sequelize.ts
Labels: status: awaiting response, type: typescript

#11294 QueryInterface.removeColumn(): fix parameter desc
  lib/query-interface.js
Labels: status: awaiting maintainer, type: docs

#11295 fix(count): fix null count with includes
  lib/model.js
  test/integration/model/count.test.js
Labels: status: awaiting maintainer, type: bug

#11300 docs(security): add responsible disclosure policy
  README.md
  SECURITY.md
Labels: status: awaiting maintainer, type: docs

#11307 feat: support include option in bulkInsert
  lib/model.js
  test/integration/model/bulk-create.test.js
  test/integration/model/bulk-create/include.test.js
  types/lib/model.d.ts
Labels: status: awaiting maintainer, type: feature

#11311 Feature: source/target keys in belongsToMany associations
  docs/associations.md
  lib/associations/belongs-to-many.js
  lib/dialects/abstract/query-generator.js
  test/integration/associations/belongs-to-many.test.js
  test/integration/dialects/postgres/query-interface.test.js
  test/unit/associations/belongs-to-many.test.js
  types/lib/associations/belongs-to-many.d.ts
Labels: hard, status: awaiting maintainer, type: feature

#11337 docs(types): Add explanatory comments to operators
  docs/querying.md
  types/lib/operators.d.ts
Labels: status: awaiting maintainer, type: docs, type: typescript

#11327 fix(query-generator): handle virtual column on associations with scopes
  lib/dialects/abstract/query-generator.js
  test/integration/model/scope/find.test.js
Labels: status: awaiting maintainer, type: bug

#11343 feat(database-error): add 'parameters' property
  lib/dialects/mariadb/query.js
  lib/dialects/mssql/query.js
  lib/dialects/mysql/query.js
  lib/dialects/postgres/query.js
  lib/errors/database-error.js
  test/integration/error.test.js
  types/lib/errors.d.ts
Labels: status: awaiting maintainer, type: other

#11360 Add support for `ON CONFLICT DO UPDATE` on SQLite 3
  lib/dialects/abstract/query-generator.js
  lib/dialects/sqlite/index.js
  lib/model.js
  test/unit/dialects/sqlite/query-generator.test.js
  test/unit/sql/insert.test.js
  types/lib/model.d.ts
Labels: dialect: sqlite, status: awaiting maintainer, type: feature

#11361 docs(model): document skipLocked
  lib/model.js
  types/lib/model.d.ts
Labels: type: docs, type: typescript

#11359 fix(types): fixed NonNullFindOptions to allow Errors
  types/lib/model.d.ts
  types/test/errors.ts
Labels: status: awaiting maintainer, type: typescript

#11368 fix(types): change raw query return type to [unknown[],unknown]
  types/lib/sequelize.d.ts
  types/test/sequelize.ts
Labels: status: awaiting maintainer, type: typescript

#11274 fix(postgres): schema for index and relations
  lib/dialects/abstract/query-generator.js
  lib/dialects/postgres/query-generator.js
  lib/model.js
  test/integration/dialects/postgres/associations.test.js
Labels: dialect: postgres, status: awaiting maintainer, type: bug

#11095 feat(postgres): minify aliases option
  .travis.yml
  lib/dialects/abstract/query-generator.js
  lib/dialects/postgres/query.js
  lib/sequelize.js
  test/config/config.js
  test/integration/associations/belongs-to-many.test.js
  test/integration/dialects/postgres/dao.test.js
  test/integration/dialects/postgres/query.test.js
  test/integration/sequelize.test.js
  test/support.js
  types/lib/sequelize.d.ts
Labels: hard, status: awaiting maintainer, type: feature
