Repository sequelize/sequelize, pull requests merged in 2019-11, with the labels that each got.

#11624 fix(types): include 'as' in IncludeThroughOptions definition
  CONTRIBUTING.md
  lib/model.js
  test/integration/associations/belongs-to-many.test.js
  types/lib/model.d.ts
  types/test/model.ts
Labels: status: awaiting response

#11654 Add section to describe logging option
  docs/manual/getting-started.md
Labels: type: docs

#11643 docs(sequelize): explain what options.retry accepts
  lib/sequelize.js
Labels: status: awaiting response, type: docs

#11674 docs(sequelize): typing of upsert interface to match code (#11673)
  types/lib/query-interface.d.ts
  types/test/query-interface.ts
Labels: status: awaiting response, type: typescript

#11628 fix(types): add isSoftDeleted to Model
  types/lib/model.d.ts
  types/test/models/User.ts
Labels: status: awaiting maintainer, type: typescript
