Repository sequelize/sequelize, pull requests merged in 2019-10, with the labels that each got.

#11456 Fix mysql showAllTables listing all tables for all databases
  .travis.yml
  docker-compose.yml
  lib/dialects/mariadb/query-generator.js
  lib/dialects/mysql/query-generator.js
  lib/query-interface.js
  test/config/mysql/mysql.sql
  test/integration/query-interface.test.js
Labels: status: awaiting response, type: bug

#11508 docs: clarifyied usage of Op.and
  docs/manual/querying.md
Labels: status: awaiting maintainer, type: docs

#11419 fix(sequelize.col): associations
  lib/dialects/abstract/query-generator.js
  test/integration/include.test.js
Labels: status: awaiting response, type: bug

#11513 State hooks don't work on instances explicitly
  docs/manual/hooks.md
Labels: status: awaiting maintainer, type: docs

#11519 chore(.github): update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: status: awaiting maintainer, type: other

#11520 fix(types): allow string and number arrays for contains operator
  test/unit/sql/where.test.js
  types/lib/model.d.ts
  types/test/where.ts
Labels: status: awaiting maintainer, type: typescript

#11476 Fix setting isolation level in MySQL and MariaDB
  lib/dialects/abstract/index.js
  lib/dialects/abstract/query-generator/transaction.js
  lib/dialects/mariadb/index.js
  lib/dialects/mysql/index.js
  lib/transaction.js
  test/integration/transaction.test.js
  test/unit/transaction.test.js
Labels: dialect: mariadb, dialect: mysql, status: awaiting response

#11499 fix(types): add Buffer to WhereValue type
  types/lib/model.d.ts
  types/test/where.ts
Labels: status: awaiting maintainer, type: typescript

#11559 fix(types): add array of Buffers to WhereValue type
  types/lib/model.d.ts
  types/test/where.ts
Labels: status: awaiting maintainer, type: typescript

#11553 Document .sequelizerc configuration options
  docs/manual/migrations.md
Labels: status: awaiting response, type: docs

#11537 feat(model): add `options.include[].right` option
  docs/manual/models-usage.md
  lib/dialects/abstract/index.js
  lib/dialects/abstract/query-generator.js
  lib/dialects/sqlite/index.js
  lib/model.js
  test/integration/include.test.js
  test/integration/model/count.test.js
  test/unit/sql/generateJoin.test.js
  test/unit/sql/select.test.js
  types/lib/model.d.ts
Labels: hard, status: awaiting maintainer, type: feature

#11538 fix(postgres): update upsert regex to match the last `RETURNING *`
  lib/dialects/postgres/query-generator.js
  test/unit/dialects/postgres/query-generator.test.js
Labels: dialect: postgres, status: awaiting maintainer, type: bug

#10851 fix(model): make .changed() deep aware
  lib/model.js
  test/unit/instance/changed.test.js
Labels: breaking change, status: in discussion, type: other

#11526 feat(postgres): change returning option to only return model attributes
  lib/dialects/abstract/query-generator.js
  lib/dialects/mssql/query-generator.js
  lib/dialects/postgres/query-generator.js
  lib/model.js
  test/integration/model.test.js
  test/integration/model/bulk-create.test.js
  test/integration/model/create.test.js
  test/unit/sql/insert.test.js
  test/unit/sql/update.test.js
Labels: breaking change, status: in discussion

#11592 Update associations.md
  docs/manual/associations.md
Labels: status: awaiting maintainer, type: docs

#11601 doc(hook): add info about belongsToMany
  docs/manual/hooks.md
Labels: status: awaiting response, type: docs

#11582 fix: fix type of methods in query-interface
  types/lib/query-interface.d.ts
  types/test/query-interface.ts
Labels: status: awaiting maintainer, type: typescript

#11614 fix(typings): Add getDatabaseName type
  types/lib/sequelize.d.ts
  types/test/sequelize.ts
Labels: status: awaiting response, type: typescript

#11612 fix(typings): Add Date type to WhereValue
  types/lib/model.d.ts
  types/test/where.ts
Labels: status: awaiting maintainer, type: typescript

#11354 fix(typings): add missing nested to Includeable
  types/lib/model.d.ts
  types/test/include.ts
Labels: status: awaiting maintainer, type: typescript

#11606 fix: escape dollarsign in sequelize.fn related to issue 11533
  lib/dialects/abstract/query-generator.js
  test/integration/instance/save.test.js
  test/integration/model/create.test.js
  test/unit/dialects/abstract/query-generator.test.js
Labels: status: awaiting maintainer, type: bug

#11620 fix(types): add missing transaction typescript types (v6-beta)
  types/lib/model.d.ts
  types/lib/transaction.d.ts
  types/test/transaction.ts
Labels: status: awaiting response, type: typescript

#11621 fix(types): add missing transaction typescript types (v5)
  types/lib/model.d.ts
  types/lib/transaction.d.ts
  types/test/transaction.ts
Labels: status: awaiting maintainer, type: typescript
