Repository sequelize/sequelize, pull requests merged in 2020-01, with the labels that each got.

#11727 Fixes #11726 - correct the overloaded method order
  types/lib/model.d.ts
Labels: type: typescript

#11833 docs(raw-queries): remove outdated info
  docs/manual/core-concepts/raw-queries.md
Labels: status: awaiting maintainer, type: docs

#11838 docs(manuals): fix missing models-definition page
  docs/manual-groups.json
Labels: status: awaiting maintainer, type: docs

#11775 feat(postgres): idle_in_transaction_session_timeout connection option
  lib/dialects/postgres/connection-manager.js
Labels: dialect: postgres, status: awaiting maintainer, type: feature

#11844 fix(typings): `queryInterface.addIndex`
  types/lib/query-interface.d.ts
  types/test/query-interface.ts
  types/type-helpers/set-required.d.ts
Labels: status: awaiting response, type: typescript

#11818 fix(types): update BelongsToManyGetAssociationsMixinOptions definition
  types/lib/associations/belongs-to-many.d.ts
  types/test/model.ts
Labels: type: typescript

#11850 docs(optimistic-locking): fix missing manual
  docs/manual/other-topics/optimistic-locking.md
Labels: status: awaiting maintainer, type: docs

#11851 refactor(docs): catch some mistakes
  docs/esdoc-config.js
  docs/manual-utils.js
Labels: status: awaiting maintainer, type: docs, type: other

#11763 fix: properly select SRID if present
  lib/dialects/mariadb/data-types.js
  lib/dialects/mysql/data-types.js
  lib/dialects/postgres/data-types.js
  test/integration/dialects/postgres/data-types.test.js
  test/integration/model/geography.test.js
  test/integration/model/geometry.test.js
  test/tmp/.gitkeep
Labels: dialect: postgres, status: awaiting maintainer, type: bug

#11852 fix(increment): broken queries
  lib/dialects/abstract/query-generator.js
  lib/model.js
  lib/query-interface.js
  test/integration/model/increment.test.js
  test/unit/dialects/mariadb/query-generator.test.js
  test/unit/dialects/mssql/query-generator.test.js
  test/unit/dialects/mysql/query-generator.test.js
  test/unit/dialects/postgres/query-generator.test.js
  test/unit/dialects/sqlite/query-generator.test.js
Labels: status: awaiting maintainer, type: bug

#11736 fix(types): adds 'hooks' to CreateOptions
  types/lib/associations/base.d.ts
  types/lib/instance-validator.d.ts
  types/lib/model.d.ts
  types/lib/sequelize.d.ts
Labels: status: awaiting response, type: typescript

#11778 fix: fixes gets on many-to-many with non-primary target key #11587
  lib/associations/belongs-to-many.js
  test/integration/associations/belongs-to-many.test.js
  test/unit/associations/belongs-to-many.test.js
Labels: status: awaiting maintainer, type: bug

#11853 feat(sqlite): automatic path provision for 'options.storage'
  lib/dialects/sqlite/connection-manager.js
  package-lock.json
  package.json
  test/integration/configuration.test.js
  test/integration/dialects/sqlite/connection-manager.test.js
Labels: dialect: sqlite, status: awaiting maintainer, type: feature

#11861 fix(sqlite): moving 'fs-jetpack' back to devDependencies
  lib/dialects/sqlite/connection-manager.js
  package-lock.json
  package.json
  test/integration/dialects/sqlite/connection-manager.test.js
Labels: status: awaiting response, type: other

#11864 refactor(*): use async/await
  test/integration/associations/belongs-to-many.test.js
  test/integration/associations/belongs-to.test.js
  test/integration/cls.test.js
  test/integration/model.test.js
Labels: status: awaiting maintainer, type: refactor

#11866 build(eslint-plugin-jsdoc): update to v20.4.0
  .eslintrc.json
  lib/associations/base.js
  lib/associations/belongs-to-many.js
  lib/associations/belongs-to.js
  lib/associations/has-many.js
  lib/associations/has-one.js
  lib/associations/helpers.js
  lib/data-types.js
  lib/dialects/abstract/connection-manager.js
  lib/dialects/abstract/query-generator.js
  lib/dialects/abstract/query-generator/helpers/quote.js
  lib/dialects/abstract/query-generator/transaction.js
  lib/dialects/abstract/query.js
  lib/dialects/mariadb/connection-manager.js
  lib/dialects/mariadb/data-types.js
  lib/dialects/mssql/data-types.js
  lib/dialects/mssql/query-generator.js
  lib/dialects/mssql/query-interface.js
  lib/dialects/mysql/connection-manager.js
  lib/dialects/mysql/data-types.js
  lib/dialects/mysql/query-generator.js
  lib/dialects/mysql/query-interface.js
  lib/dialects/postgres/data-types.js
  lib/dialects/postgres/query-interface.js
  lib/dialects/postgres/query.js
  lib/dialects/sqlite/data-types.js
  lib/dialects/sqlite/query-interface.js
  lib/dialects/sqlite/query.js
  lib/errors/bulk-record-error.js
  lib/errors/connection-error.js
  lib/errors/database-error.js
  lib/errors/optimistic-lock-error.js
  lib/errors/validation-error.js
  lib/hooks.js
  lib/instance-validator.js
  lib/model-manager.js
  lib/model.js
  lib/query-interface.js
  lib/sequelize.js
  lib/transaction.js
  lib/utils.js
  package-lock.json
  package.json
Labels: status: awaiting maintainer, type: other

#11875 refactor(tests): use async/await
  test/integration/query-interface.test.js
Labels: status: awaiting maintainer, type: refactor

#11876 refactor(tests): use async/await
  test/integration/operators.test.js
  test/integration/pool.test.js
Labels: status: awaiting maintainer, type: refactor

#11762 docs(model): fix findOne docs
  lib/model.js
  types/lib/model.d.ts
Labels: status: awaiting maintainer, type: docs, type: refactor

#11843 fix(typings): `comparator` arg of `Sequelize.where`
  types/lib/sequelize.d.ts
  types/test/where.ts
Labels: status: awaiting maintainer, type: typescript

#11874 build(docs): save space
  package.json
Labels: status: awaiting maintainer, type: docs, type: other
