Repository sequelize/sequelize, pull requests merged in 2020-04, with the labels that each got.

#12014 Fix requires for bundlers like webpack
  lib/dialects/abstract/connection-manager.js
Labels: status: awaiting response, type: other

#12015 Update model.d.ts
  types/lib/model.d.ts
Labels: status: awaiting response, type: typescript

#12088 feat(belongs-to-many): allow creation of paranoid join tables
  lib/associations/belongs-to-many.js
  test/integration/associations/belongs-to-many.test.js
  types/lib/associations/belongs-to-many.d.ts
  types/test/model.ts
Labels: status: awaiting response

#12090 fix(mssql) insert record failure because of BOOLEAN column type
  lib/dialects/mssql/query.js
  test/integration/dialects/mssql/regressions.test.js
Labels: status: awaiting response
