Repository sequelize/sequelize, pull requests merged in 2020-02, with the labels that each got.

#11888 docs(manual): fix typos in assocs manual
  docs/manual/core-concepts/assocs.md
Labels: status: awaiting maintainer, type: docs

#11865 refactor(lib): new `joinSQLFragments` util
  lib/data-types.js
  lib/dialects/abstract/query-generator.js
  lib/dialects/mariadb/data-types.js
  lib/dialects/mariadb/query-generator.js
  lib/dialects/mssql/query-generator.js
  lib/dialects/mysql/data-types.js
  lib/dialects/mysql/query-generator.js
  lib/utils.js
  lib/utils/join-sql-fragments.js
  test/unit/dialects/mariadb/query-generator.test.js
  test/unit/dialects/mssql/query-generator.test.js
  test/unit/dialects/postgres/query-generator.test.js
Labels: status: awaiting maintainer, type: refactor

#11882 fix(types): Allow augmentation on model interfaces
  types/index.d.ts
Labels: status: awaiting maintainer, type: typescript

#11867 other(find-all): throw on empty attributes
  lib/dialects/abstract/query-generator.js
  lib/dialects/mssql/query-generator.js
  test/integration/model/findAll.test.js
Labels: breaking change, status: awaiting maintainer, type: other

#11596 Support `{ plain: true }` in typescript typings for sequelize.query
  types/lib/sequelize.d.ts
  types/test/sequelize.ts
Labels: status: awaiting response, type: typescript

#11929 Support `{ plain: true }` in typescript typings for sequelize.query
  types/lib/sequelize.d.ts
  types/test/sequelize.ts
Labels: status: awaiting maintainer, type: typescript

#11893 fix(model): count() code generation for distinct rows
  lib/model.js
  test/integration/model/count.test.js
Labels: status: awaiting response

#11877 [v4] fix(sqlite): properly catch errors
  lib/dialects/sqlite/query.js
  test/integration/dialects/sqlite/issue-11862.test.js
Labels: P1: important, status: awaiting maintainer, type: bug

#11947 docs: improve query-interface removeIndex indexNameOrAttributes @param
  lib/query-interface.js
Labels: status: awaiting response, type: docs
