Repository sequelize/sequelize, pull requests merged in 2021-12, with the labels that each got.

#13406 feat(dialect): snowflake dialect support
  .github/workflows/ci.yml
  lib/data-types.js
  lib/dialects/abstract/query-generator/helpers/quote.js
  lib/dialects/snowflake/connection-manager.js
  lib/dialects/snowflake/data-types.js
  lib/dialects/snowflake/index.js
  lib/dialects/snowflake/query-generator.js
  lib/dialects/snowflake/query-interface.js
  lib/dialects/snowflake/query.js
  lib/sequelize.js
  lib/sql-string.js
  package.json
  test/config/config.js
  test/integration/dialects/snowflake/connector-manager.test.js
  test/integration/dialects/snowflake/smoke.test.js
  test/unit/dialect-module-configuration.test.js
  test/unit/dialects/snowflake/errors.test.js
  test/unit/dialects/snowflake/query-generator.test.js
  test/unit/dialects/snowflake/query.test.js
  test/unit/sql/change-column.test.js
  test/unit/sql/create-table.test.js
  test/unit/sql/data-types.test.js
  test/unit/sql/delete.test.js
  test/unit/sql/group.test.js
  test/unit/sql/index.test.js
  test/unit/sql/insert.test.js
  test/unit/sql/offset-limit.test.js
  test/unit/sql/order.test.js
  test/unit/sql/remove-column.test.js
  test/unit/sql/select.test.js
  test/unit/sql/show-constraints.test.js
  test/unit/sql/update.test.js
  test/unit/sql/where.test.js
  yarn.lock
Labels: type: feature, hard, dialect: new

#13710 feat(types): transition lib/errors
  lib/dialects/mssql/async-queue.js
  lib/dialects/mssql/async-queue.ts
  lib/errors/aggregate-error.js
  lib/errors/aggregate-error.ts
  lib/errors/association-error.ts
  lib/errors/base-error.ts
  lib/errors/bulk-record-error.js
  lib/errors/bulk-record-error.ts
  lib/errors/connection-error.ts
  lib/errors/connection/access-denied-error.ts
  lib/errors/connection/connection-acquire-timeout-error.ts
  lib/errors/connection/connection-refused-error.ts
  lib/errors/connection/connection-timed-out-error.ts
  lib/errors/connection/host-not-found-error.ts
  lib/errors/connection/host-not-reachable-error.ts
  lib/errors/connection/invalid-connection-error.ts
  lib/errors/database-error.js
  lib/errors/database-error.ts
  lib/errors/database/exclusion-constraint-error.js
  lib/errors/database/exclusion-constraint-error.ts
  lib/errors/database/foreign-key-constraint-error.js
  lib/errors/database/foreign-key-constraint-error.ts
  lib/errors/database/timeout-error.js
  lib/errors/database/timeout-error.ts
  lib/errors/database/unknown-constraint-error.js
  lib/errors/database/unknown-constraint-error.ts
  lib/errors/eager-loading-error.ts
  lib/errors/empty-result-error.ts
  lib/errors/index.js
  lib/errors/index.ts
  lib/errors/instance-error.ts
  lib/errors/optimistic-lock-error.js
  lib/errors/optimistic-lock-error.ts
  lib/errors/query-error.ts
  lib/errors/sequelize-scope-error.ts
  lib/errors/validation-error.js
  lib/errors/validation-error.ts
  lib/errors/validation/unique-constraint-error.js
  lib/errors/validation/unique-constraint-error.ts
  test/integration/error.test.js
  test/integration/model/bulk-create.test.js
Labels: type: refactor, type: typescript

#13759 docs(typescript): add plugin to parse TS files
  docs/esdoc-config.js
  esdoc-ts.js
Labels: type: docs

#13689 Add support for native ESM named exports
  build.js
  index.mjs
  package.json
  test/unit/esm-named-exports.test.js
Labels: status: in discussion

#13768 docs(jsdoc): update entry point descriptions.
  index.js
Labels: type: docs

#13431 Added the link to sequelize-yugabytedb repo in README
  README.md
Labels: stale, type: other, dialect: new

#13443 docs: correct documentation on bulkCreate updateOnDuplicate option
  lib/model.js
  types/lib/model.d.ts
Labels: type: docs, status: awaiting response

#13736 fix(model.d): fix findAndCountAll.count type
  types/lib/model.d.ts
Labels: type: typescript

#13731 refactor(operators): convert operators to typescript
  lib/operators.js
  lib/operators.ts
  types/index.d.ts
  types/lib/model.d.ts
Labels: type: refactor, type: typescript

#13807 fix(13804): use schema for ARRAY(ENUM) type name
  lib/dialects/postgres/data-types.js
  test/integration/dialects/postgres/dao.test.js
Labels: dialect: postgres, status: wip

#13825 refactor(model): remove unnecessary option fallback
  lib/model.js
Labels: type: refactor

#13818 fix(data-types): moment object throwing error
  lib/data-types.js
  lib/dialects/db2/data-types.js
  lib/dialects/mariadb/data-types.js
  lib/dialects/mysql/data-types.js
  lib/dialects/postgres/connection-manager.js
  lib/dialects/snowflake/data-types.js
  test/integration/model/findAll.test.js
Labels: type: bug, type: refactor
