Repository sequelize/sequelize, pull requests merged in 2021-11, with the labels that each got.

#13600 fix: queryinterface does not provide existing fkeys when schema is used
  lib/dialects/postgres/query-interface.js
  test/integration/query-interface/getForeignKeyReferencesForTable.test.js
Labels: type: bug

#13586 docs(engine): update MSSQL and PostgreSQL
  ENGINE.md
  lib/dialects/mariadb/index.js
  lib/dialects/mssql/index.js
  lib/dialects/mysql/index.js
  lib/dialects/postgres/index.js
  lib/dialects/sqlite/index.js
  package.json
Labels: type: docs

#13622 docs(contact): update contributors emails
  CONTACT.md
Labels: type: docs

#12801 Fix MSSQL sub query issue occurring with renamed primary key fields
  lib/dialects/abstract/query-generator.js
  test/integration/associations/has-one.test.js
Labels: type: bug, regression

#13632 meta: persist lockfile
  .github/workflows/ci.yml
  .gitignore
  yarn.lock
Labels: dependency

#13348 fix(types): rename types and update CONTRIBUTING docs
  CONTRIBUTING.md
  types/lib/model.d.ts
  types/lib/sequelize.d.ts
Labels: stale

#13661 fix(types): add specifc tojson type in model.d.ts
  types/lib/model.d.ts
  types/test/model.ts
Labels: type: typescript

#13686 ci: add other ts versions to ci
  .github/workflows/ci.yml
Labels: type: typescript

#13594 fix(upsert): fall back to DO NOTHING if no update key values provided
  lib/dialects/abstract/query-generator.js
  lib/dialects/mssql/query-generator.js
  lib/dialects/mssql/query.js
  lib/dialects/mysql/query-interface.js
  lib/dialects/postgres/query.js
  lib/model.js
  test/integration/model/upsert.test.js
Labels: status: in discussion

#13684 fix(types): add instance member declaration
  types/lib/sequelize.d.ts
  types/test/sequelize.ts
Labels: type: typescript

#12642 Create aws-lambda.md
  docs/manual/other-topics/aws-lambda.md
Labels: type: docs

#13693 hotfix(docs): add aws-lamda route
  docs/manual-groups.json
Labels: type: bug

#13700 docs: add logo
  README.md
  docs/css/style.css
  docs/index.md
Labels: type: docs

#13717 fix(types): add Col to where Ops
  types/lib/model.d.ts
  types/test/where.ts
Labels: type: typescript

#13712 fix(data-types): unnecessary warning when getting data with DATE dataTypes
  lib/dialects/mariadb/data-types.js
  lib/dialects/mysql/data-types.js
Labels: type: bug, dialect: mysql

#13408 Add .schema to Options interface
  types/lib/sequelize.d.ts
Labels: type: typescript
