Repository sequelize/sequelize, pull requests merged in 2021-03, with the labels that each got.

#13093 fix(types): Allow transaction to be null in Transactionable interface (#13092).
  types/lib/model.d.ts
  types/test/transaction.ts
Labels: status: awaiting response

#13096 feat(add-constraint): add defferable option
  lib/dialects/abstract/query-generator.js
  lib/dialects/abstract/query-interface.js
  test/integration/sequelize/deferrable.test.js
  types/lib/query-interface.d.ts
Labels: dialect: postgres, status: awaiting response

#13108 Fix missing property in ValidationErrorItem
  lib/errors/validation-error.js
  types/lib/errors.d.ts
Labels: type: typescript

#13043 fix(queryGenerator): use AND for not/between
  lib/dialects/abstract/query-generator.js
  test/unit/sql/where.test.js
Labels: status: awaiting response

#13042 fix(types): adds missing function signature to Model.prototype.previous() types
  types/lib/model.d.ts
  types/test/model.ts
Labels: status: awaiting response
