Repository sequelize/sequelize, pull requests merged in 2021-06, with the labels that each got.

#13324 docs(model-querying-basics.md): Fix a typo in the docs
  docs/manual/core-concepts/model-querying-basics.md
Labels: type: docs

#13260 bump inflection dependency
  package.json
Labels: dependency, type: bug

#13216 fix(typings): restrict update typings
  types/lib/model.d.ts
  types/test/update.ts
Labels: type: typescript
