Repository sequelize/sequelize, pull requests merged in 2022-03, with the labels that each got.

#14110 feat: merge scope where conditions using the and operator
  src/model.js
  test/integration/model/scope/destroy.test.js
  test/integration/model/scope/find.test.js
  test/integration/model/scope/findAndCountAll.test.js
  test/integration/model/scope/update.test.js
  test/support.js
  test/unit/model/include.test.js
  test/unit/model/scope.test.js
Labels: type: feature, P4: nice to have

#14097 fix: mssql commentTemplate handling table object
  src/dialects/mssql/query-generator.js
  test/unit/dialects/mssql/query-generator.test.js
Labels: type: bug

#14188 feat: stop testing against TypeScript < 4.4
  .github/workflows/ci.yml
  docs/manual/other-topics/typescript.md
Labels: dependency, type: typescript

#14152 feat(scopes): add whereScopeStrategy to merge where scopes with Op.and
  src/model.d.ts
  src/model.js
  test/support.js
  test/unit/model/scope.test.js
Labels: type: feature

#14216 docs: update renamed field
  docs/manual/other-topics/migrations.md
Labels: type: docs

#14181 feat: reserve `::`, `->` syntax in attribute names
  docs/manual/other-topics/upgrade-to-v7.md
  src/model.js
  test/unit/model/define.test.js
Labels: breaking change

#14229 fix(types): remove non-exist types in query interface
  src/dialects/abstract/query-interface.d.ts
  test/types/query-interface.ts
Labels: type: typescript

#14022 fix(types): make `WhereOptions` more accurate
  docs/manual/other-topics/other-data-types.md
  src/dialects/abstract/index.ts
  src/dialects/postgres/index.js
  src/model.d.ts
  src/sequelize.d.ts
  src/utils/sequelize-method.ts
  test/support.js
  test/support2.ts
  test/types/connection.ts
  test/types/models/User.ts
  test/types/where.ts
  test/unit/sql/where.test.js
  test/unit/sql/where.test.ts
Labels: type: typescript

#14148 feat(types): make `Model.init` aware of pre-configured foreign keys
  docs/manual/other-topics/typescript.md
  src/model.d.ts
  test/types/infer-attributes.ts
  test/types/typescriptDocs/Define.ts
  test/types/typescriptDocs/DefineNoAttributes.ts
  test/types/typescriptDocs/ModelInit.ts
  test/types/typescriptDocs/ModelInitNoAttributes.ts
Labels: type: typescript

#14282 build: accept `@typeParam` and `@internal` tags in typedoc
  .eslintrc.js
Labels: type: other

#14293 docs: add Code of Conduct
  CODE-OF-CONDUCT.md
  CONTACT.md
Labels: type: other

#14234 build: remove v6 docs from repository
  .github/workflows/ci.yml
  docs/esdoc-config.js
  docs/images/bitovi-logo.png
  docs/images/clevertech.png
  docs/images/connected-cars.png
  docs/images/ermeshotels-logo.png
  docs/images/filsh.png
  docs/images/logo-snaplytics-green.png
  docs/images/logo.png
  docs/images/metamarkets.png
  docs/images/shutterstock.png
  docs/images/slack.svg
  docs/images/walmart-labs-logo.png
  docs/index.md
  docs/manual-utils.js
  docs/manual/advanced-association-concepts/advanced-many-to-many.md
  docs/manual/advanced-association-concepts/association-scopes.md
  docs/manual/advanced-association-concepts/creating-with-associations.md
  docs/manual/advanced-association-concepts/eager-loading.md
  docs/manual/advanced-association-concepts/polymorphic-associations.md
  docs/manual/core-concepts/assocs.md
  docs/manual/core-concepts/getters-setters-virtuals.md
  docs/manual/core-concepts/getting-started.md
  docs/manual/core-concepts/model-basics.md
  docs/manual/core-concepts/model-instances.md
  docs/manual/core-concepts/model-querying-basics.md
  docs/manual/core-concepts/model-querying-finders.md
  docs/manual/core-concepts/paranoid.md
  docs/manual/core-concepts/raw-queries.md
  docs/manual/core-concepts/validations-and-constraints.md
  docs/manual/moved/associations.md
  docs/manual/moved/data-types.md
  docs/manual/moved/models-definition.md
  docs/manual/moved/models-usage.md
  docs/manual/moved/querying.md
  docs/manual/other-topics/aws-lambda.md
  docs/manual/other-topics/connection-pool.md
  docs/manual/other-topics/constraints-and-circularities.md
  docs/manual/other-topics/dialect-specific-things.md
  docs/manual/other-topics/extending-data-types.md
  docs/manual/other-topics/hooks.md
  docs/manual/other-topics/indexes.md
  docs/manual/other-topics/legacy.md
  docs/manual/other-topics/legal.md
  docs/manual/other-topics/migrations.md
  docs/manual/other-topics/naming-strategies.md
  docs/manual/other-topics/optimistic-locking.md
  docs/manual/other-topics/other-data-types.md
  docs/manual/other-topics/query-interface.md
  docs/manual/other-topics/read-replication.md
  docs/manual/other-topics/resources.md
  docs/manual/other-topics/scopes.md
  docs/manual/other-topics/sub-queries.md
  docs/manual/other-topics/transactions.md
  docs/manual/other-topics/typescript.md
  docs/manual/other-topics/upgrade-to-v6.md
  docs/manual/other-topics/whos-using.md
  docs/transforms/header-customization.js
Labels: type: docs
