Repository sequelize/sequelize, pull requests merged in 2022-09, with the labels that each got.

#14964 fix(types): backport #14704 for v6
  src/model.d.ts
  test/types/model.ts
Labels: type: typescript

#14963 fix: decode encoded value from `urlParts.pathname` for `database` option
  src/utils/url.ts
  test/unit/utils/utils.test.ts
Labels: type: bug

#14993 fix(types): add missing model hooks types
  src/hooks.d.ts
  test/types/hooks.ts
Labels: type: typescript

#14999 feat: implement proper schema support in mysql, snowflake, add `queryInterface.listDatabases`
  src/dialects/abstract/index.ts
  src/dialects/abstract/query-generator.d.ts
  src/dialects/abstract/query-generator.js
  src/dialects/abstract/query-interface.d.ts
  src/dialects/abstract/query-interface.js
  src/dialects/db2/query-generator.js
  src/dialects/ibmi/query-generator.js
  src/dialects/mariadb/query-generator.js
  src/dialects/mssql/index.js
  src/dialects/mssql/query-generator.js
  src/dialects/mysql/index.js
  src/dialects/mysql/query-generator.js
  src/dialects/mysql/query.js
  src/dialects/postgres/index.js
  src/dialects/postgres/query-generator.js
  src/dialects/snowflake/index.js
  src/dialects/snowflake/query-generator.js
  src/dialects/sqlite/query-generator.js
  src/utils/check.ts
  test/integration/associations/belongs-to-many.test.js
  test/integration/associations/belongs-to.test.js
  test/integration/associations/has-one.test.js
  test/integration/dialects/mariadb/query-interface.test.js
  test/integration/include/schema.test.js
  test/integration/model.test.js
  test/integration/model/bulk-create.test.js
  test/integration/model/sync.test.js
  test/integration/query-interface.test.js
  test/integration/query-interface/changeColumn.test.js
  test/integration/query-interface/create-drop-list-database.test.ts
  test/integration/query-interface/createTable.test.js
  test/integration/query-interface/removeColumn.test.js
  test/integration/schema.test.js
  test/integration/sequelize.test.js
  test/support.ts
  test/unit/dialects/mariadb/query-generator.test.js
  test/unit/dialects/mssql/query-generator.test.js
  test/unit/dialects/mysql/query-generator.test.js
  test/unit/dialects/postgres/query-generator.test.js
  test/unit/dialects/snowflake/query-generator.test.js
  test/unit/query-generator/create-database-query.test.ts
  test/unit/query-generator/create-schema-query.test.ts
  test/unit/query-generator/drop-database-query.test.ts
  test/unit/query-generator/drop-schema-query.test.ts
  test/unit/query-generator/list-databases-query.test.ts
  test/unit/query-generator/list-schemas-query.test.ts
  test/unit/sql/create-schema.test.js
  test/unit/sql/create-table.test.js
  test/unit/sql/delete.test.js
  test/unit/sql/index.test.js
  test/unit/sql/remove-column.test.js
  test/unit/sql/where.test.ts
Labels: type: bug, type: feature

#15065 docs(model): Added paranoid option for Model.BelongsToMany.through
  src/model.js
Labels: type: docs

#15049 docs: add missing ssl options for sequelize instance (v6)
  src/sequelize.js
Labels: type: docs
