Repository sequelize/sequelize, pull requests merged in 2022-01, with the labels that each got.

#13878 docs(dialect-specific): add details about dialectOptions
  docs/manual/other-topics/dialect-specific-things.md
Labels: type: docs

#13890 fix: improve ModelCtor / ModelStatic typing
  types/lib/model.d.ts
  types/test/models/User.ts
  types/test/models/UserPost.ts
  types/test/type-helpers/deep-writable.ts
Labels: type: typescript

#13899 fix: fix typings for queries with {plain: true} option
  types/lib/sequelize.d.ts
  types/test/sequelize.ts
Labels: type: typescript

#13908 docs(license): change contributors to authors
  LICENSE
Labels: type: refactor

#13900 fix _logQuery crashing when logging bigints
  lib/dialects/abstract/query.js
  lib/utils.js
  test/integration/sequelize/query.test.js
  test/unit/dialects/abstract/query.test.js
Labels: type: bug

#13902 docs: `joinTableAttributes` in `belongsToMany` mixin
  docs/manual/core-concepts/assocs.md
Labels: type: docs

#13911 fix(sequelize.d) fix type of `options` arg in `Sequelize.define` method
  types/lib/sequelize.d.ts
Labels: type: typescript

#13940 feat(types): add typings for DataTypes.TSVECTOR
  types/lib/data-types.d.ts
Labels: type: typescript

#13786 fix(model.d): fix type for `count` and `findAndCountAll`
  docs/manual/core-concepts/model-querying-finders.md
  package.json
  types/lib/model.d.ts
  types/test/model-count.ts
  types/test/model.ts
Labels: type: typescript

#13491 fix(types): add hooks to InstanceDestroyOptions type
  types/lib/model.d.ts
  types/test/destroy.ts
Labels: type: typescript

#13389 fix(types): add missing fields to FindOr{Create,Build}Options
  types/lib/model.d.ts
  types/test/model.ts
Labels: type: typescript

#13946 docs: introduce new version of sequelize README
  README.md
Labels: type: docs

#13945 fix(types): fix QueryInterface#bulkInsert attribute arg type
  types/lib/data-types.d.ts
  types/lib/query-interface.d.ts
  types/test/data-types.ts
  types/test/query-interface.ts
Labels: type: typescript

#13951 fix: don't call overloaded versions of find functions internally
  lib/model.js
  test/unit/model/bulk-create.test.js
  test/unit/model/find-all.test.js
  test/unit/model/find-by-pk.test.js
  test/unit/model/find-one.test.js
  test/unit/model/get-attributes.test.js
  test/unit/model/remove-attribute.test.js
Labels: type: refactor

#13954 feat(types): drop TypeScript < 4.1
  .github/workflows/ci.yml
  docs/manual/other-topics/typescript.md
Labels: type: typescript

#13956 build: improve eslint config (part 2)
  .eslintrc.js
  docs/run-docs-transforms.js
  lib/dialects/abstract/query.js
  lib/dialects/mssql/query-generator.js
  lib/dialects/snowflake/connection-manager.js
  lib/errors/validation-error.ts
  lib/instance-validator.js
  lib/sequelize.js
  lib/sql-string.js
  lib/transaction.ts
  lib/utils/class-to-invokable.ts
  lib/utils/join-sql-fragments.ts
  package.json
  sscce.js
  test/integration/cls.test.js
  test/integration/dialects/sqlite/dao-factory.test.js
  test/integration/model.test.js
  test/integration/model/geography.test.js
  test/integration/replication.test.js
  test/integration/sequelize/log.test.js
  test/integration/sequelize/query.test.js
  test/integration/trigger.test.js
  test/unit/dialects/mssql/query.test.js
  test/unit/dialects/mysql/query.test.js
  test/unit/dialects/postgres/query-generator.test.js
  test/unit/dialects/snowflake/query.test.js
  test/unit/instance/save.test.js
  test/unit/logger.test.ts
  test/unit/sql/data-types.test.js
  test/unit/sql/select.test.js
  yarn.lock
Labels: type: refactor

#13909 feat(types): add `InferAttributes` utility type
  docs/manual/other-topics/typescript.md
  types/lib/associations/belongs-to-many.d.ts
  types/lib/associations/belongs-to.d.ts
  types/lib/associations/has-many.d.ts
  types/lib/associations/has-one.d.ts
  types/lib/hooks.d.ts
  types/lib/model.d.ts
  types/lib/query-interface.d.ts
  types/lib/sequelize.d.ts
  types/lib/utils.d.ts
  types/test/attributes.ts
  types/test/create.ts
  types/test/infer-attributes.ts
  types/test/models/User.ts
  types/test/models/UserGroup.ts
  types/test/typescriptDocs/Define.ts
  types/test/typescriptDocs/DefineNoAttributes.ts
  types/test/typescriptDocs/ModelInit.ts
  types/test/typescriptDocs/ModelInitNoAttributes.ts
Labels: type: typescript

#14005 docs: document breaking change from #13951
  docs/manual/other-topics/upgrade-to-v7.md
Labels: type: docs

#14002 fix(types): deduplicate error typings
  lib/errors/aggregate-error.ts
  lib/errors/base-error.ts
  lib/errors/bulk-record-error.ts
  lib/errors/database-error.ts
  lib/errors/database/exclusion-constraint-error.ts
  lib/errors/database/foreign-key-constraint-error.ts
  lib/errors/database/unknown-constraint-error.ts
  lib/errors/optimistic-lock-error.ts
  lib/errors/validation-error.ts
  lib/errors/validation/unique-constraint-error.ts
  types/index.d.ts
  types/lib/errors.d.ts
  types/test/attributes.ts
  types/test/errors.ts
  types/test/hooks.ts
  types/test/model.ts
  types/test/query-interface.ts
  types/test/sequelize.ts
Labels: type: bug, type: typescript

#13985 docs: clarify how the `limit` option works
  lib/dialects/mssql/query-generator.js
  lib/operators.ts
  test/support.js
  test/unit/sql/select.test.js
  types/lib/model.d.ts
Labels: type: docs
