Repository sequelize/sequelize, pull requests merged in 2022-11, with the labels that each got.

#15210 fix(types): add to cast to projection alias
  src/model.d.ts
  test/types/find-all.ts
  test/unit/query-generator/select-query.test.ts
Labels: type: typescript

#15119 feat(postgres): support for `ADD COLUMN IF NOT EXISTS` and `DROP COLUMN IF EXISTS`
  src/dialects/abstract/index.ts
  src/dialects/abstract/query-generator.d.ts
  src/dialects/abstract/query-generator.js
  src/dialects/abstract/query-interface.d.ts
  src/dialects/abstract/query-interface.js
  src/dialects/db2/index.js
  src/dialects/db2/query-generator.js
  src/dialects/ibmi/index.js
  src/dialects/ibmi/query-generator.js
  src/dialects/mariadb/index.js
  src/dialects/mssql/index.js
  src/dialects/mssql/query-generator.js
  src/dialects/mysql/index.js
  src/dialects/mysql/query-generator.js
  src/dialects/postgres/index.js
  src/dialects/postgres/query-generator.js
  src/dialects/snowflake/index.js
  src/dialects/snowflake/query-generator.js
  src/dialects/sqlite/index.js
  src/dialects/sqlite/query-generator.js
  test/unit/query-generator/add-column-query.test.ts
  test/unit/query-generator/remove-column-query.test.ts
Labels: type: feature

#15208 fix(types): add instance.dataValues property to model.d.ts
  src/model.d.ts
  test/unit/model/remove-attribute.test.ts
Labels: type: typescript

#15240 fix(types): add instance.dataValues property to model.d.ts
  src/model.d.ts
Labels: type: typescript

#15286 meta: remove CI badge
  README.md
Labels: type: other

#15292 feat: replace CLS with ALS, enable ALS by default, discourage unmanaged transactions
  package.json
  src/model-internals.ts
  src/model.d.ts
  src/model.js
  src/sequelize-typescript.ts
  src/sequelize.d.ts
  src/sequelize.js
  src/transaction.ts
  test/integration/als.test.ts
  test/integration/associations/belongs-to-many.test.js
  test/integration/associations/belongs-to.test.js
  test/integration/associations/has-many.test.js
  test/integration/associations/has-one.test.js
  test/integration/cls.test.js
  test/integration/instance/decrement.test.js
  test/integration/instance/destroy.test.js
  test/integration/instance/increment.test.js
  test/integration/instance/reload.test.js
  test/integration/instance/save.test.js
  test/integration/instance/update.test.js
  test/integration/model.test.js
  test/integration/model/bulk-create.test.js
  test/integration/model/create.test.js
  test/integration/model/findAll.test.js
  test/integration/model/findOne.test.js
  test/integration/model/json.test.js
  test/integration/sequelize.test.js
  test/integration/sequelize.transaction.test.ts
  test/integration/sequelize/query.test.js
  test/integration/transaction.test.js
  test/support.ts
  test/types/sequelize.ts
  test/types/transaction.ts
  test/unit/esm-named-exports.test.js
  test/unit/model/find-or-create.test.js
  test/unit/transaction.test.js
  test/unit/transaction.test.ts
  yarn.lock
Labels: topic: als, funded

#15304 meta: rework how to manage issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: other

#15306 fix: fix parameters not being replaced when after $$ strings
  src/utils/sql.ts
  test/unit/utils/sql.test.ts
Labels: type: bug

#15108 feat: restrict instance methods if no primary key
  src/dialects/abstract/query-interface.js
  src/model.js
  test/integration/instance/decrement.test.js
  test/integration/instance/destroy.test.js
  test/integration/instance/increment.test.js
  test/integration/instance/reload.test.js
  test/integration/instance/restore.test.ts
  test/integration/instance/save.test.js
  test/integration/instance/update.test.js
  test/unit/instance/decrement.test.js
  test/unit/instance/destroy.test.js
  test/unit/instance/increment.test.js
  test/unit/instance/reload.test.js
  test/unit/instance/restore.test.js
  test/unit/instance/save.test.js
  test/unit/instance/update.test.ts
Labels: hacktoberfest-accepted
