Repository sequelize/sequelize, pull requests merged in 2022-04, with the labels that each got.

#14313 docs: fix dead link in API reference
  docs/transforms/header-customization.js
Labels: type: docs

#14319 chore(error): add `snowflake` to default throw new Error
  src/sequelize.js
  test/integration/configuration.test.js
Labels: type: refactor

#14321 docs(op): fix queries example for [Op.any]
  src/model.d.ts
  src/operators.ts
Labels: type: docs

#14318 feat: use native `Error#cause` in Sequelize errors
  src/dialects/db2/query.js
  src/dialects/ibmi/query.js
  src/dialects/mariadb/query.js
  src/dialects/mssql/query.js
  src/dialects/mysql/query.js
  src/dialects/postgres/query.js
  src/dialects/snowflake/query.js
  src/dialects/sqlite/query.js
  src/errors/association-error.ts
  src/errors/base-error.ts
  src/errors/bulk-record-error.ts
  src/errors/connection-error.ts
  src/errors/connection/access-denied-error.ts
  src/errors/connection/connection-acquire-timeout-error.ts
  src/errors/connection/connection-refused-error.ts
  src/errors/connection/connection-timed-out-error.ts
  src/errors/connection/host-not-found-error.ts
  src/errors/connection/host-not-reachable-error.ts
  src/errors/connection/invalid-connection-error.ts
  src/errors/database-error.ts
  src/errors/database/exclusion-constraint-error.ts
  src/errors/database/foreign-key-constraint-error.ts
  src/errors/database/timeout-error.ts
  src/errors/database/unknown-constraint-error.ts
  src/errors/eager-loading-error.ts
  src/errors/empty-result-error.ts
  src/errors/instance-error.ts
  src/errors/optimistic-lock-error.ts
  src/errors/query-error.ts
  src/errors/sequelize-scope-error.ts
  src/errors/validation-error.ts
  src/errors/validation/unique-constraint-error.ts
  src/utils/deprecations.ts
Labels: type: feature

#14323 docs: restore Model api reference & make fail on error
  docs.sh
  package.json
  src/model.js
Labels: type: docs

#14337 feat: add Model.{getInitialModel,withoutScope}, rename schema+(un)?scope
  src/model.d.ts
  src/model.js
  src/utils/deprecations.ts
  test/unit/model/schema.test.js
  test/unit/model/scope.test.js
  test/unit/model/variants.ts
Labels: type: feature

#14360 feat: add `isModelStatic`, `isSameInitialModel`
  src/dialects/abstract/query-generator.js
  src/index.d.ts
  src/index.mjs
  src/model.js
  src/sequelize.js
  src/utils/model-utils.ts
  test/unit/utils/model-utils.test.ts
Labels: type: feature

#14359 feat: simplify withSchema API
  src/model.d.ts
  src/model.js
  test/integration/model/schema.test.js
  test/support.d.ts
  test/unit/model/schema.test.ts
  test/unit/model/scope.test.ts
Labels: type: feature, type: refactor

#14362 fix(types): accept `ibmi` as dialect name
  src/sequelize.d.ts
Labels: type: typescript

#14384 build(sqlite): use regular package instead of vscode fork
  package.json
  yarn.lock
Labels: dependency, type: other

#14386 feat: add `noPrimaryKey` to prevent creating a default PK attribute
  src/model.d.ts
  src/model.js
  test/unit/model/define.test.js
Labels: type: feature

#14407 refactor: migrate test support to ts
  package.json
  src/deferrable.ts
  src/dialects/abstract/index.ts
  src/dialects/abstract/query-generator.d.ts
  src/dialects/abstract/query-interface.d.ts
  src/sequelize.d.ts
  src/transaction.ts
  test/chai-extensions.d.ts
  test/config/config.ts
  test/integration/configuration.test.js
  test/integration/dialects/abstract/connection-manager.test.js
  test/integration/sequelize.test.js
  test/support.js
  test/support.ts
  test/support2.ts
  test/tsconfig.json
  test/unit/dialects/abstract/query-interface.test.ts
  test/unit/model/variants.ts
  test/unit/sql/where.test.ts
  test/unit/utils/model-utils.test.ts
  yarn.lock
Labels: type: typescript

#14404 fix: dont treat `?&` or `?|` as replacements
  src/sql-string.js
  test/integration/sequelize/query.test.js
Labels: type: bug

#14333 docs: clean up model docs
  src/associations/base.d.ts
  src/associations/belongs-to-many.d.ts
  src/associations/belongs-to.d.ts
  src/associations/has-many.d.ts
  src/associations/has-one.d.ts
  src/dialects/abstract/query-generator.js
  src/dialects/abstract/query-interface.d.ts
  src/dialects/abstract/query.d.ts
  src/hooks.d.ts
  src/model-manager.d.ts
  src/model.d.ts
  src/model.js
  src/sequelize.d.ts
  src/transaction.ts
  src/utils/check.ts
  src/utils/deprecations.ts
  src/utils/index.ts
  test/types/findByPk.ts
  test/types/query-interface.ts
  test/types/type-helpers/deep-writable.ts
  test/types/where.ts
  test/unit/model/define.test.js
  test/unit/model/find-all.test.js
Labels: type: docs
