Repository sequelize/sequelize, pull requests merged in 2022-07, with the labels that each got.

#14670 meta: lint PR title
  .github/workflows/pr-title.yml
  .husky/commit-msg
  CONTRIBUTING.md
  package.json
  yarn.lock
Labels: meta

#14700 fix: don't treat `\` as escape in standard strings, support E-strings, support vars after `->>` operator
  src/dialects/abstract/index.ts
  src/dialects/mariadb/index.js
  src/dialects/mysql/index.js
  src/dialects/postgres/index.js
  src/utils/sql.ts
  test/support.ts
  test/unit/utils/sql.test.ts
Labels: type: bug

#14713 feat: support typescript >= 4.5's module resolution
  package.json
Labels: type: typescript

#14704 fix(types): align the return value of increment and decrement with actual behavior
  src/model.d.ts
  test/types/model.ts
Labels: type: typescript

#13927 fix: pass CLS transaction to model hooks
  src/model-internals.ts
  src/model.js
  test/integration/cls.test.js
Labels: type: bug

#14070 fix(sqlite): Fix removeColumn and changeColumn foreign key issues for the sqlite dialect
  src/dialects/sqlite/query-generator.js
  src/dialects/sqlite/query-interface.js
  test/integration/dialects/sqlite/test.sqlite
  test/integration/query-interface.test.js
  test/integration/query-interface/changeColumn.test.js
  test/integration/query-interface/removeColumn.test.js
  test/unit/dialects/sqlite/query-generator.test.js
  test/unit/sql/remove-column.test.js
Labels: type: bug

#14738 fix: take scope into account when setting associated models with belongsToMany's `.setX`
  src/associations/belongs-to-many.ts
  test/integration/associations/scope.test.js
Labels: type: bug
