Repository sequelize/sequelize, pull requests merged in 2022-02, with the labels that each got.

#14018 fix(types): correct typing definitions for `Sequelize.where`
  test/unit/sql/where.test.js
  types/lib/model.d.ts
  types/lib/sequelize.d.ts
  types/test/sequelize.ts
  types/test/where.ts
Labels: type: typescript

#13990 fix(types): improve branded types
  types/lib/model.d.ts
  types/test/infer-attributes.ts
  types/test/models/UserGroup.ts
Labels: type: typescript

#13983 fix(types): accept `$nested.syntax$` in WhereAttributeHash
  types/lib/model.d.ts
  types/test/findOne.ts
Labels: type: typescript

#14017 feat(types): make `Model.getAttributes` stricter
  src/model.d.ts
  test/types/model.ts
Labels: type: typescript

#14094 build: generate jsdoc from src instead of lib
  docs/ROUTER.txt
  docs/css/style.css
  docs/esdoc-config.js
  docs/manual/core-concepts/assocs.md
  docs/manual/core-concepts/getting-started.md
  docs/manual/core-concepts/model-basics.md
  docs/manual/core-concepts/model-instances.md
  docs/manual/core-concepts/model-querying-basics.md
  docs/manual/core-concepts/raw-queries.md
  docs/manual/other-topics/aws-lambda.md
  docs/manual/other-topics/connection-pool.md
  docs/manual/other-topics/hooks.md
  docs/manual/other-topics/indexes.md
  docs/manual/other-topics/query-interface.md
  docs/manual/other-topics/scopes.md
  docs/transforms/group-data-types.js
Labels: type: docs

#14096 build: generate jsdoc from src instead of lib (v6)
  docs/ROUTER.txt
  docs/css/style.css
  docs/esdoc-config.js
  docs/manual/core-concepts/assocs.md
  docs/manual/core-concepts/getting-started.md
  docs/manual/core-concepts/model-basics.md
  docs/manual/core-concepts/model-instances.md
  docs/manual/core-concepts/model-querying-basics.md
  docs/manual/core-concepts/raw-queries.md
  docs/manual/other-topics/aws-lambda.md
  docs/manual/other-topics/connection-pool.md
  docs/manual/other-topics/hooks.md
  docs/manual/other-topics/indexes.md
  docs/manual/other-topics/query-interface.md
  docs/manual/other-topics/scopes.md
  docs/transforms/group-data-types.js
Labels: type: docs

#14090 fix(postgres): correctly re-acquire connection while using pg-native
  src/dialects/postgres/query.js
Labels: type: bug, dialect: postgres

#14126 fix(types): update 'replication' option property
  src/sequelize.d.ts
Labels: type: typescript

#14137 fix(types): missing snowflake and db2 dialects
  src/sequelize.d.ts
Labels: type: typescript

#14132 meta: update comment in bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type: docs

#13943 build: add nodejs/node update authors integration
  .eslintrc.js
  .github/workflows/authors.yml
  AUTHORS
  dev/update-authors.js
Labels: type: other

#14156 fix(types): drop excess argument for upsert
  src/dialects/abstract/query-interface.d.ts
  test/types/query-interface.ts
Labels: type: typescript

#14154 fix(types): export `GroupedCountResultItem` interface
  src/model.d.ts
Labels: type: typescript

#14146 fix(types): support union in CreationAttributes
  src/utils.d.ts
  test/types/create.ts
Labels: type: bug, type: typescript

#14155 fix(types): update return type of `Model.update`
  src/model.d.ts
  test/types/model.ts
Labels: type: typescript

#13782 refactor: convert utils to typescript
  package.json
  src/dialects/abstract/query-generator.js
  src/dialects/abstract/query.js
  src/dialects/db2/query-generator.js
  src/dialects/sqlite/query-generator.js
  src/index.d.ts
  src/model.d.ts
  src/sequelize.d.ts
  src/utils.d.ts
  src/utils.js
  src/utils/array.ts
  src/utils/check.ts
  src/utils/dialect.ts
  src/utils/format.ts
  src/utils/index.ts
  src/utils/object.ts
  src/utils/sequelize-method.ts
  src/utils/string.ts
  test/integration/utils.test.js
  test/types/sequelize.ts
  test/types/where.ts
  test/unit/dialects/abstract/query-interface.test.ts
  test/unit/utils.test.js
  test/unit/utils/check.test.ts
  tsconfig.json
  yarn.lock
Labels: type: typescript
